### ISSUE TITLE
problem with initial run

### ISSUE THREAD

**Issue by wwirzbicki** [OpenBankProject/OBP-API#1169]
I have a problem with initial running of OBP-API. I just cloned the repo and typed
./mvn.sh jetty:run

Server starts with some errors and when I browse to localhost:8080 i get screen full of boxes like on the screen below
![image](https://user-images.githubusercontent.com/7860388/49428333-0e384280-f7a6-11e8-87be-ff0f69449e7c.png)

Errors from server log:
`2018-12-04 09:14:13 main HTTPProvider [ERROR] ********** Failed to Boot! Your application may not run properly
java.lang.NullPointerException: Looking for Connection Identifier ConnectionIdentifier(lift) but failed to find either a JNDI data source with the name lift or a lift connection manager with the correct name
	at net.liftweb.db.DB.$anonfun$newConnection$14(DB.scala:182)
	at net.liftweb.common.EmptyBox.openOr(Box.scala:910)
	at net.liftweb.db.DB.newConnection(DB.scala:181)
	at net.liftweb.db.DB.getConnection(DB.scala:286)
	at net.liftweb.db.DB.use(DB.scala:680)
	at net.liftweb.db.DB.use$(DB.scala:679)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.mapper.Schemifier$.schemify(Schemifier.scala:91)
	at net.liftweb.mapper.Schemifier$.schemify(Schemifier.scala:57)
	at net.liftweb.mapper.Schemifier$.schemify(Schemifier.scala:54)
	at bootstrap.liftweb.Boot.schemifyAll(Boot.scala:468)
	at bootstrap.liftweb.Boot.boot(Boot.scala:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.liftweb.util.ClassHelpers.$anonfun$createInvoker$2(ClassHelpers.scala:357)
	at net.liftweb.http.DefaultBootstrap$.$anonfun$boot$1(LiftRules.scala:2250)
	at net.liftweb.common.Full.map(Box.scala:854)
	at net.liftweb.http.DefaultBootstrap$.boot(LiftRules.scala:2250)
	at net.liftweb.http.provider.HTTPProvider.bootLift(HTTPProvider.scala:88)
	at net.liftweb.http.provider.HTTPProvider.bootLift$(HTTPProvider.scala:83)
	at net.liftweb.http.LiftFilter.bootLift(LiftServlet.scala:1063)
	at net.liftweb.http.provider.servlet.ServletFilterProvider.init(ServletFilterProvider.scala:40)
	at net.liftweb.http.provider.servlet.ServletFilterProvider.init$(ServletFilterProvider.scala:35)
	at net.liftweb.http.LiftFilter.init(LiftServlet.scala:1063)
	at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:97)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:713)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.jetty.plugin.Jetty6PluginWebAppContext.doStart(Jetty6PluginWebAppContext.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.plugin.Jetty6PluginServer.start(Jetty6PluginServer.java:132)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:454)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:396)
	at org.mortbay.jetty.plugin.AbstractJettyRunMojo.execute(AbstractJettyRunMojo.java:210)
	at org.mortbay.jetty.plugin.Jetty6RunMojo.execute(Jetty6RunMojo.java:184)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2018-12-04 09:14:13 main HTTPProvider [ERROR] ------------------------------------------------------------------
2018-12-04 09:14:13 main HTTPProvider [ERROR] ------------------------------------------------------------------
2018-12-04 09:14:13 main HTTPProvider [ERROR] ------------------------------------------------------------------
2018-12-04 09:14:13 main HTTPProvider [ERROR] ------------------------------------------------------------------
2018-12-04 09:14:13 main HTTPProvider [ERROR] ------------------------------------------------------------------
[INFO] Started SelectChannelConnector@0.0.0.0:8080
`

**Comment by tawoe** [comment]
Did you copy sample.props.template to default.props in src/main/resources/props/ ?

**Comment by wwirzbicki** [comment]
No, I did not. After copying everything works fine. I cannot find that instruction in the manual (readme.md). Perhaps it should be added there.
