### ISSUE TITLE
duplicate key value violates unique constraint "mappedkyccheck_mid"

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#209]
Got this a few times on the JBFG sandbox:

```


Mon Nov 07 04:51:42 UTC 2016: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "mappedkyccheck_mid"
  Detail: Key (mid)=(98FRd987auhf87jab) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:307)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:305)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:677)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:676)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.db.DB$class.runPreparedStatement(DB.scala:675)
	at net.liftweb.db.DB$class.prepareStatement(DB.scala:618)
	at net.liftweb.db.DB$$anon$1.prepareStatement(DB.scala:40)
	at net.liftweb.db.PostgreSqlDriver$.performInsertWithGenKeys(Driver.scala:304)
	at net.liftweb.db.DriverType.performInsert(Driver.scala:94)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:919)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:867)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.mapper.MetaMapper$class.save(MetaMapper.scala:866)
	at code.kycchecks.MappedKycCheck$.save(MappedKycChecksProvider.scala:62)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply$mcZ$sp(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.util.Safe$.runSafe(Safe.scala:36)
	at net.liftweb.mapper.Mapper$class.runSafe(Mapper.scala:54)
	at code.kycchecks.MappedKycCheck.runSafe(MappedKycChecksProvider.scala:33)
	at net.liftweb.mapper.Mapper$class.save(Mapper.scala:87)
	at code.kycchecks.MappedKycCheck.save(MappedKycChecksProvider.scala:33)
	at code.kycchecks.MappedKycChecksProvider$.addKycChecks(MappedKycChecksProvider.scala:29)
	at code.api.v2_0_0.APIMethods200$$$$$$6ee630a697ee6ccf88fa1733fde37fea$$$$anonfun$apply$4.apply$mcZ$sp(APIMethods200.scala:666)
	at code.util.Helper$.booleanToBox(Helper.scala:52)
	at code.api.v2_0_0.APIMethods200$$$$$$d98334e540b56428f1742739d2527690$$$$nonfun$apply$97.apply(APIMethods200.scala:665)
	at code.api.v2_0_0.APIMethods200$$$$$$d98334e540b56428f1742739d2527690$$$$nonfun$apply$97.apply(APIMethods200.scala:664)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_0_0.APIMethods200$$$$$$f36921c8829ac8d1a4a8fae736f42452$$$$nonfun$apply$95.apply(APIMethods200.scala:664)
	at code.api.v2_0_0.APIMethods200$$$$$$f36921c8829ac8d1a4a8fae736f42452$$$$nonfun$apply$95.apply(APIMethods200.scala:663)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_0_0.APIMethods200$$$$$$edb1f0b984f4e814fe45d9a9ca941fb1$$$$nonfun$apply$93.apply(APIMethods200.scala:663)
	at code.api.v2_0_0.APIMethods200$$$$$$edb1f0b984f4e814fe45d9a9ca941fb1$$$$nonfun$apply$93.apply(APIMethods200.scala:662)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_0_0.APIMethods200$$$$$$c68a047ec7245cb6f8c314e25314f54$$$$nonfun$apply$90.apply(APIMethods200.scala:662)
	at code.api.v2_0_0.APIMethods200$$$$$$c68a047ec7245cb6f8c314e25314f54$$$$nonfun$apply$90.apply(APIMethods200.scala:661)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_0_0.APIMethods200$$$$$$7cfb7d1289ed471fc55da6484b9957ce$$$$$applyOrElse$15.apply(APIMethods200.scala:661)
	at code.api.v2_0_0.APIMethods200$$$$$$7cfb7d1289ed471fc55da6484b9957ce$$$$$applyOrElse$15.apply(APIMethods200.scala:659)
	at code.api.OBPRestHelper$class.failIfBadAuthorizationHeader(OBPRestHelper.scala:136)
	at code.api.v2_1_0.OBPAPI2_1_0$.failIfBadAuthorizationHeader(OBPAPI2_1_0.scala:43)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:195)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:189)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:223)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:219)
	at net.liftweb.http.rest.RestHelper$class.apply(RestHelper.scala:522)
	at code.api.v2_1_0.OBPAPI2_1_0$.apply(OBPAPI2_1_0.scala:43)
	at code.api.v2_1_0.OBPAPI2_1_0$.apply(OBPAPI2_1_0.scala:43)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.common.Full.map(Box.scala:610)
	at net.liftweb.util.NamedPF$.applyBox(NamedPartialFunction.scala:97)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply$mcZ$sp(LiftServlet.scala:281)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
	at net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.withReq(S.scala:1685)
	at net.liftweb.http.S$.withReq(S.scala:47)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
	at net.liftweb.http.S$class.statelessInit(S.scala:1302)
	at net.liftweb.http.S$.statelessInit(S.scala:47)
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:279)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:365)
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34)
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147)
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1327)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60)
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74)
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1022)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marko-md** [comment]
@sebtesobe Have you tried to insert the same JSON data twice at the endpoint /banks/BANK_ID/customers/CUSTOMER_ID/kyc_check?

**Comment by sebtesobe** [comment]
I have no idea how this came about. I only get these kind of messages automatically via email.

**Comment by marko-md** [comment]
@simonredfern Do we need a guard at this endpoint which will forbid second attempt of posting the same data and provide a fine message as a feedback?

**Comment by simonredfern** [comment]
No - We had an invalid unique index which should be removed with drop index mappedkycstatus_mcustomernumber; I've just added a migration for that too

**Comment by simonredfern** [comment]
Ah sorry, My comment above is valid for kyc status. We *do* need a guard on the id to ensure its unique. This is the same for all the KYC related POSTs. See https://github.com/OpenBankProject/OBP-API/issues/215

**Comment by sebtesobe** [comment]
During the last 24 hours, we got ca. 26 exceptions like this on the JBFG sandbox. Last deployment to that sandbox was less than 2 days ago, so i assume it's not fixed yet?

**Comment by sebtesobe** [comment]
It seems like it is not happening anymore, can we close this ticket?
