### ISSUE TITLE
java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#210]
Got heaps of these on JBFG sandbox:

```
Mon Nov 07 00:37:42 UTC 2016: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at code.fx.fx$.convert(fx.scala:24)
	at code.bankconnectors.LocalMappedConnector$.getChallengeThreshold(LocalMappedConnector.scala:38)
	at code.bankconnectors.Connector$class.createTransactionRequestv210(Connector.scala:328)
	at code.bankconnectors.LocalMappedConnector$.createTransactionRequestv210(LocalMappedConnector.scala:29)
	at code.api.v2_1_0.APIMethods210$$$$$$5cf71de9c9f35dc6c15eef9acae825$$$$nonfun$apply$59.apply(APIMethods210.scala:297)
	at code.api.v2_1_0.APIMethods210$$$$$$5cf71de9c9f35dc6c15eef9acae825$$$$nonfun$apply$59.apply(APIMethods210.scala:295)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$608a723429412e917ba3756d36afc$$$$nonfun$apply$57.apply(APIMethods210.scala:295)
	at code.api.v2_1_0.APIMethods210$$$$$$608a723429412e917ba3756d36afc$$$$nonfun$apply$57.apply(APIMethods210.scala:294)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$b6f7f07c8b2f107451f813a92a63a93a$$$$nonfun$apply$56.apply(APIMethods210.scala:294)
	at code.api.v2_1_0.APIMethods210$$$$$$b6f7f07c8b2f107451f813a92a63a93a$$$$nonfun$apply$56.apply(APIMethods210.scala:293)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$161588b318daa5a073bbe0e5c8f0d8b8$$$$nonfun$apply$55.apply(APIMethods210.scala:293)
	at code.api.v2_1_0.APIMethods210$$$$$$161588b318daa5a073bbe0e5c8f0d8b8$$$$nonfun$apply$55.apply(APIMethods210.scala:278)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$802598e3954f90df3166dc951e9ac41a$$$$nonfun$apply$52.apply(APIMethods210.scala:278)
	at code.api.v2_1_0.APIMethods210$$$$$$802598e3954f90df3166dc951e9ac41a$$$$nonfun$apply$52.apply(APIMethods210.scala:276)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$6373dccfc68a36c61e9c48377eab2c$$$$nonfun$apply$50.apply(APIMethods210.scala:276)
	at code.api.v2_1_0.APIMethods210$$$$$$6373dccfc68a36c61e9c48377eab2c$$$$nonfun$apply$50.apply(APIMethods210.scala:273)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$9a2f3b30b4e276fba0752323ebcef6$$$$nonfun$apply$49.apply(APIMethods210.scala:273)
	at code.api.v2_1_0.APIMethods210$$$$$$9a2f3b30b4e276fba0752323ebcef6$$$$nonfun$apply$49.apply(APIMethods210.scala:272)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$23c4210df78193cd72dca306ee019c9$$$$nonfun$apply$47.apply(APIMethods210.scala:272)
	at code.api.v2_1_0.APIMethods210$$$$$$23c4210df78193cd72dca306ee019c9$$$$nonfun$apply$47.apply(APIMethods210.scala:271)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$21a567f1413b69a73c153933a3dbded$$$$nonfun$apply$45.apply(APIMethods210.scala:271)
	at code.api.v2_1_0.APIMethods210$$$$$$21a567f1413b69a73c153933a3dbded$$$$nonfun$apply$45.apply(APIMethods210.scala:265)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$e7ea6a40b7e73873656bc5833f7ae$$$$nonfun$apply$41.apply(APIMethods210.scala:265)
	at code.api.v2_1_0.APIMethods210$$$$$$e7ea6a40b7e73873656bc5833f7ae$$$$nonfun$apply$41.apply(APIMethods210.scala:247)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$7a4e85ebd628979617f7b72db8830c$$$$nonfun$apply$34.apply(APIMethods210.scala:247)
	at code.api.v2_1_0.APIMethods210$$$$$$7a4e85ebd628979617f7b72db8830c$$$$nonfun$apply$34.apply(APIMethods210.scala:245)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$29ab9760974910c02a518885f71ec2$$$$nonfun$apply$32.apply(APIMethods210.scala:245)
	at code.api.v2_1_0.APIMethods210$$$$$$29ab9760974910c02a518885f71ec2$$$$nonfun$apply$32.apply(APIMethods210.scala:242)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$ba206acf68dd9da7b6aa2074a8c08240$$$$nonfun$apply$30.apply(APIMethods210.scala:242)
	at code.api.v2_1_0.APIMethods210$$$$$$ba206acf68dd9da7b6aa2074a8c08240$$$$nonfun$apply$30.apply(APIMethods210.scala:240)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$fbae4b529e35da68e3484eeaf06338b4$$$$nonfun$apply$28.apply(APIMethods210.scala:240)
	at code.api.v2_1_0.APIMethods210$$$$$$fbae4b529e35da68e3484eeaf06338b4$$$$nonfun$apply$28.apply(APIMethods210.scala:237)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.api.v2_1_0.APIMethods210$$$$$$9c9fb3a8942fe4728556b0f0743d24b5$$$$n$applyOrElse$3.apply(APIMethods210.scala:237)
	at code.api.v2_1_0.APIMethods210$$$$$$9c9fb3a8942fe4728556b0f0743d24b5$$$$n$applyOrElse$3.apply(APIMethods210.scala:230)
	at code.api.OBPRestHelper$class.failIfBadAuthorizationHeader(OBPRestHelper.scala:136)
	at code.api.v2_1_0.OBPAPI2_1_0$.failIfBadAuthorizationHeader(OBPAPI2_1_0.scala:43)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:195)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:189)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:223)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:219)
	at net.liftweb.http.rest.RestHelper$class.apply(RestHelper.scala:522)
	at code.api.v2_1_0.OBPAPI2_1_0$.apply(OBPAPI2_1_0.scala:43)
	at code.api.v2_1_0.OBPAPI2_1_0$.apply(OBPAPI2_1_0.scala:43)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.common.Full.map(Box.scala:610)
	at net.liftweb.util.NamedPF$.applyBox(NamedPartialFunction.scala:97)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply$mcZ$sp(LiftServlet.scala:281)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
	at net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.withReq(S.scala:1685)
	at net.liftweb.http.S$.withReq(S.scala:47)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
	at net.liftweb.http.S$class.statelessInit(S.scala:1302)
	at net.liftweb.http.S$.statelessInit(S.scala:47)
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:279)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:365)
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34)
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147)
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1327)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60)
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74)
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1022)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by marko-md** [comment]
@sebtesobe Do you have data below in the props file?
## Transaction request challenge threshold. Level at which challenge is created and needs to be answered.
## The Currency is EUR. Connector implementations may convert the value to the transaction request currency.
## Connector implementation may well provide dynamic response
## These settings are of the form transactionRequests_challenge_threshold_UPPERCASETYPE=INTEGER
transactionRequests_challenge_threshold_SANDBOX_TAN=1000
transactionRequests_challenge_threshold_SEPA=1000

**Comment by marko-md** [comment]
@sebtesobe Which currencies have you used in transaction?

**Comment by sebtesobe** [comment]
The properties related to transactionRequests in the props file are:
```
transactionRequests_enabled=true
transactionRequests_connector=mapped
transactionRequests_supported_types=SANDBOX_TAN
```
Is the threshold mandatory?


Unfortunately, i cannot tell you what action led to this traceback or what currencies were used. I only get these type of messages automatically as an email form the sandboxes.

**Comment by marko-md** [comment]
@sebtesobe It should use default value 1000 if property does not exist.
@simonredfern Do we need to guard endpoint or refine the message "NoSuchElementException" if there is no information needed for converting one currency to another?

**Comment by simonredfern** [comment]
@marko-md please add guard and message if exchange currency is not supported

**Comment by sebtesobe** [comment]
We are not receiving exception emails on that anymore. Can we close this ticket?

**Comment by constantine2nd** [comment]
Fixed.
