### ISSUE TITLE
value too long for type character varying(10)

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#214]
Got a couple of these last week on apisandbox:

```
Thu Nov 03 14:35:43 UTC 2016: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(10)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:307)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:305)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:677)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:676)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.db.DB$class.runPreparedStatement(DB.scala:675)
	at net.liftweb.db.DB$class.prepareStatement(DB.scala:618)
	at net.liftweb.db.DB$$anon$1.prepareStatement(DB.scala:40)
	at net.liftweb.db.PostgreSqlDriver$.performInsertWithGenKeys(Driver.scala:304)
	at net.liftweb.db.DriverType.performInsert(Driver.scala:94)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:919)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:867)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.mapper.MetaMapper$class.save(MetaMapper.scala:866)
	at code.model.dataAccess.MappedBankAccount$.save(MappedBankAccount.scala:57)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply$mcZ$sp(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.util.Safe$.runSafe(Safe.scala:36)
	at net.liftweb.mapper.Mapper$class.runSafe(Mapper.scala:54)
	at code.model.dataAccess.MappedBankAccount.runSafe(MappedBankAccount.scala:9)
	at net.liftweb.mapper.Mapper$class.save(Mapper.scala:87)
	at code.model.dataAccess.MappedBankAccount.save(MappedBankAccount.scala:9)
	at net.liftweb.mapper.Mapper$class.saveMe(Mapper.scala:82)
	at code.model.dataAccess.MappedBankAccount.saveMe(MappedBankAccount.scala:9)
	at code.bankconnectors.LocalMappedConnector$.code$bankconnectors$LocalMappedConnector$$createAccountIfNotExisting(LocalMappedConnector.scala:487)
	at code.bankconnectors.LocalMappedConnector$$anonfun$createSandboxBankAccount$1.apply(LocalMappedConnector.scala:460)
	at code.bankconnectors.LocalMappedConnector$$anonfun$createSandboxBankAccount$1.apply(LocalMappedConnector.scala:456)
	at net.liftweb.common.Full.map(Box.scala:610)
	at code.bankconnectors.LocalMappedConnector$.createSandboxBankAccount(LocalMappedConnector.scala:456)
	at code.bankconnectors.Connector$class.createSandboxBankAccount(Connector.scala:568)
	at code.bankconnectors.LocalMappedConnector$.createSandboxBankAccount(LocalMappedConnector.scala:29)
	at code.snippet.CreateTestAccou$$$$3f24816a5a5341b953589deff57d2bf$$$$nonfun$apply$12.apply(CreateTestAccountForm.scala:84)
	at code.snippet.CreateTestAccou$$$$3f24816a5a5341b953589deff57d2bf$$$$nonfun$apply$12.apply(CreateTestAccountForm.scala:82)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$2ed8fdcccd17b36617841ab02427f8$$$$nonfun$apply$11.apply(CreateTestAccountForm.scala:82)
	at code.snippet.CreateTestAccou$$$$2ed8fdcccd17b36617841ab02427f8$$$$nonfun$apply$11.apply(CreateTestAccountForm.scala:81)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$8b99c7aa249c9d0cf814938f16dc56$$$$anonfun$apply$9.apply(CreateTestAccountForm.scala:81)
	at code.snippet.CreateTestAccou$$$$8b99c7aa249c9d0cf814938f16dc56$$$$anonfun$apply$9.apply(CreateTestAccountForm.scala:80)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$30b15bdb67796f36624d29bedba26f5$$$$anonfun$apply$7.apply(CreateTestAccountForm.scala:80)
	at code.snippet.CreateTestAccou$$$$30b15bdb67796f36624d29bedba26f5$$$$anonfun$apply$7.apply(CreateTestAccountForm.scala:79)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccountForm$$anonfun$createAccount$3.apply(CreateTestAccountForm.scala:79)
	at code.snippet.CreateTestAccountForm$$anonfun$createAccount$3.apply(CreateTestAccountForm.scala:78)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccountForm$.createAccount(CreateTestAccountForm.scala:78)
	at code.snippet.CreateTestAccountForm$$anonfun$1.apply(CreateTestAccountForm.scala:27)
	at code.snippet.CreateTestAccountForm$$anonfun$1.apply(CreateTestAccountForm.scala:26)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at scala.collection.immutable.List.map(List.scala:273)
	at net.liftweb.http.S$NFuncHolder.apply(S.scala:185)
	at net.liftweb.http.S$ProxyFuncHolder.apply(S.scala:114)
	at net.liftweb.http.LiftSession$$anonfun$net$liftweb$http$LiftSession$$buildFunc$1$2.apply(LiftSession.scala:783)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at scala.collection.immutable.List.map(List.scala:277)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:788)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at net.liftweb.http.LiftSession.runParams(LiftSession.scala:787)
	at net.liftweb.http.LiftServlet.liftedTree2$1(LiftServlet.scala:491)
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$runAjax(LiftServlet.scala:490)
	at net.liftweb.http.LiftServlet$$anonfun$handleAjax$1.apply(LiftServlet.scala:635)
	at net.liftweb.http.LiftServlet$$anonfun$handleAjax$1.apply(LiftServlet.scala:555)
	at net.liftweb.http.LiftServlet$$anonfun$extractVersions$1.apply(LiftServlet.scala:464)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11.apply(Vars.scala:546)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(Vars.scala:545)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9.apply(Vars.scala:544)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8.apply(Vars.scala:543)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1.apply(Vars.scala:542)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1.apply(Vars.scala:542)
	at net.liftweb.http.S$PageStateHolder.runInContext(S.scala:228)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28$$anonfun$16.apply(LiftSession.scala:459)
	at net.liftweb.util.AnyVarTrait$class.doWith(AnyVar.scala:234)
	at net.liftweb.util.AnyVar.doWith(AnyVar.scala:89)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28.apply(LiftSession.scala:458)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28.apply(LiftSession.scala:454)
	at scala.Option.map(Option.scala:146)
	at net.liftweb.http.RenderVersion$$anonfun$15.apply(LiftSession.scala:454)
	at net.liftweb.http.RenderVersion$$anonfun$15.apply(LiftSession.scala:453)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at net.liftweb.http.RenderVersion$.doWith(LiftSession.scala:453)
	at net.liftweb.http.LiftServlet.extractVersions(LiftServlet.scala:464)
	at net.liftweb.http.LiftServlet.handleAjax(LiftServlet.scala:555)
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$dispatchStatefulRequest(LiftServlet.scala:421)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
	at net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.withReq(S.scala:1685)
	at net.liftweb.http.S$.withReq(S.scala:47)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
	at net.liftweb.http.S$class.init(S.scala:1284)
	at net.liftweb.http.S$.init(S.scala:47)
	at net.liftweb.http.LiftServlet.doSession$1(LiftServlet.scala:300)
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:310)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:365)
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34)
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147)
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1327)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60)
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74)
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1022)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marko-md** [comment]
@sebtesobe At OBP-API there is a form, Create Bank Account, in which you can fill next data:
- Bank
- Desired Account Id
- Desired Account Currency
- Desired Initial Balance
In this case seem that entered "Desired Account Currency" exceeded a 10 chars limit.
@simonredfern Do we need to extend current checks of form fields?

**Comment by simonredfern** [comment]
Input currency must be ISO_4217 3 letter string. i.e. Ccy in http://www.currency-iso.org/dam/downloads/lists/list_one.xml

**Comment by sebtesobe** [comment]
Have not received those exceptions lately. Can we close this ticket?
