### ISSUE TITLE
Could not initialize class code.views.AkkaMapperViews on bnpparibas-api.o.c

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#368]
Got 12 of these exceptions just now on https://bnpparibas-api.openbankproject.com:

```
Mon Feb 06 08:00:47 UTC 2017: java.lang.NoClassDefFoundError: Could not initialize class code.views.AkkaMapperViews$
	at code.views.Views$.buildOne(Views.scala:15)
	at code.views.Views$$anon$1$$anonfun$$lessinit$greater$1.apply(Views.scala:11)
	at code.views.Views$$anon$1$$anonfun$$lessinit$greater$1.apply(Views.scala:11)
	at net.liftweb.util.Vendor$$anon$1.vend(Maker.scala:210)
	at net.liftweb.util.Vendor$class.apply(Maker.scala:182)
	at net.liftweb.util.Vendor$$anon$1.apply(Maker.scala:209)
	at net.liftweb.util.SimpleInjector$Inject$$anonfun$make$1.apply(Maker.scala:88)
	at net.liftweb.util.SimpleInjector$Inject$$anonfun$make$1.apply(Maker.scala:88)
	at net.liftweb.common.EmptyBox.or(Box.scala:703)
	at net.liftweb.util.SimpleInjector$Inject.make(Maker.scala:88)
	at net.liftweb.util.SimpleInjector$Inject.vend(Maker.scala:83)
	at code.model.dataAccess.BankAccountCreation$.createOwnerView(BankAccountCreationDispatcher.scala:94)
	at code.model.dataAccess.BankAccountCreation$.setAsOwner(BankAccountCreationDispatcher.scala:86)
	at code.snippet.CreateTestAccou$$$$6abff5e0efbff0795a70f256274f4aed$$$$nonfun$apply$13.apply(CreateTestAccountForm.scala:90)
	at code.snippet.CreateTestAccou$$$$6abff5e0efbff0795a70f256274f4aed$$$$nonfun$apply$13.apply(CreateTestAccountForm.scala:88)
	at net.liftweb.common.Full.map(Box.scala:610)
	at code.snippet.CreateTestAccou$$$$3758d48392337d51a0b6bf7a31c38d$$$$nonfun$apply$12.apply(CreateTestAccountForm.scala:88)
	at code.snippet.CreateTestAccou$$$$3758d48392337d51a0b6bf7a31c38d$$$$nonfun$apply$12.apply(CreateTestAccountForm.scala:86)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$c98db4b825ea0fb699d79fcc81e1d4c$$$$nonfun$apply$11.apply(CreateTestAccountForm.scala:86)
	at code.snippet.CreateTestAccou$$$$c98db4b825ea0fb699d79fcc81e1d4c$$$$nonfun$apply$11.apply(CreateTestAccountForm.scala:85)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$666364b1a58d7de23fbb339267d3d34$$$$anonfun$apply$9.apply(CreateTestAccountForm.scala:85)
	at code.snippet.CreateTestAccou$$$$666364b1a58d7de23fbb339267d3d34$$$$anonfun$apply$9.apply(CreateTestAccountForm.scala:84)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccou$$$$5b8d201fa981c4fb65346c782f1d969$$$$anonfun$apply$7.apply(CreateTestAccountForm.scala:84)
	at code.snippet.CreateTestAccou$$$$5b8d201fa981c4fb65346c782f1d969$$$$anonfun$apply$7.apply(CreateTestAccountForm.scala:83)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccountForm$$anonfun$createAccount$4.apply(CreateTestAccountForm.scala:83)
	at code.snippet.CreateTestAccountForm$$anonfun$createAccount$4.apply(CreateTestAccountForm.scala:82)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at code.snippet.CreateTestAccountForm$.createAccount(CreateTestAccountForm.scala:82)
	at code.snippet.CreateTestAccountForm$$anonfun$1.apply(CreateTestAccountForm.scala:27)
	at code.snippet.CreateTestAccountForm$$anonfun$1.apply(CreateTestAccountForm.scala:26)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at scala.collection.immutable.List.map(List.scala:273)
	at net.liftweb.http.S$NFuncHolder.apply(S.scala:185)
	at net.liftweb.http.S$ProxyFuncHolder.apply(S.scala:114)
	at net.liftweb.http.LiftSession$$anonfun$net$liftweb$http$LiftSession$$buildFunc$1$2.apply(LiftSession.scala:783)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at scala.collection.immutable.List.map(List.scala:277)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:788)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at net.liftweb.http.LiftSession.runParams(LiftSession.scala:787)
	at net.liftweb.http.LiftServlet.liftedTree2$1(LiftServlet.scala:491)
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$runAjax(LiftServlet.scala:490)
	at net.liftweb.http.LiftServlet$$anonfun$handleAjax$1.apply(LiftServlet.scala:635)
	at net.liftweb.http.LiftServlet$$anonfun$handleAjax$1.apply(LiftServlet.scala:555)
	at net.liftweb.http.LiftServlet$$anonfun$extractVersions$1.apply(LiftServlet.scala:464)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11.apply(Vars.scala:546)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9$$anonfun$apply$10.apply(Vars.scala:545)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8$$anonfun$apply$9.apply(Vars.scala:544)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1$$anonfun$apply$8.apply(Vars.scala:543)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1.apply(Vars.scala:542)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$generateSnapshotRestorer$1.apply(Vars.scala:542)
	at net.liftweb.http.S$PageStateHolder.runInContext(S.scala:228)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28$$anonfun$16.apply(LiftSession.scala:459)
	at net.liftweb.util.AnyVarTrait$class.doWith(AnyVar.scala:234)
	at net.liftweb.util.AnyVar.doWith(AnyVar.scala:89)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28.apply(LiftSession.scala:458)
	at net.liftweb.http.RenderVersion$$anonfun$15$$anonfun$apply$28.apply(LiftSession.scala:454)
	at scala.Option.map(Option.scala:146)
	at net.liftweb.http.RenderVersion$$anonfun$15.apply(LiftSession.scala:454)
	at net.liftweb.http.RenderVersion$$anonfun$15.apply(LiftSession.scala:453)
	at net.liftweb.common.Full.flatMap(Box.scala:612)
	at net.liftweb.http.RenderVersion$.doWith(LiftSession.scala:453)
	at net.liftweb.http.LiftServlet.extractVersions(LiftServlet.scala:464)
	at net.liftweb.http.LiftServlet.handleAjax(LiftServlet.scala:555)
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$dispatchStatefulRequest(LiftServlet.scala:421)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
	at net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.withReq(S.scala:1685)
	at net.liftweb.http.S$.withReq(S.scala:47)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
	at net.liftweb.http.S$class.init(S.scala:1284)
	at net.liftweb.http.S$.init(S.scala:47)
	at net.liftweb.http.LiftServlet.doSession$1(LiftServlet.scala:300)
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:310)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:365)
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34)
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147)
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1327)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60)
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74)
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1022)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marko-md** [comment]
```Scala
object Views  extends SimpleInjector {

  val views = new Inject(buildOne _) {}
 
  //TODO Remove MapperViews when AkkaMapperViews is optimized and stable
  def buildOne: Views = MapperViews
  //def buildOne: Views = AkkaMapperViews
  
}
```
@sebtesobe Please double check that AkkaMapperViews is commented out, and MapperViews is used. Akka connector is still experimental.

**Comment by sebtesobe** [comment]
It looks like @moule3053 deployed the API three times today after my report. Has it been sorted, Mulugeta?

**Comment by sebtesobe** [comment]
Just saw db0094a622362c0242b2f2b1c987f8d40dc4bb2b and 1d1c1cb02620a73e8131ac08e2a61db5179ef4f0. Maybe BNPP just happened to be deployed in between those.

**Comment by sebtesobe** [comment]
Oops,  yesterday was 6th of February, but last deployment was on 6th of January. Sorry @moule3053 , i am missing a month in my work life ;)

**Comment by sebtesobe** [comment]
Since i git 26 exception emails over night, i decided to redeploy. If there won't be any more exceptions like this in the next couple of days, i will close this ticket.
