### ISSUE TITLE
Duplicate key value violates unique constraint "resourceuser_pk"

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#393]
I deployed the latest API to a few sandboxes yesterday and ran the migration commands on the database and since then we get a few of those messages all over (as usual, i do not know what the user did):

```
Mon Feb 13 15:29:37 UTC 2017: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "resourceuser_pk"
  Detail: Key (id)=(2) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:307)
	at net.liftweb.db.PostgreSqlDriver$$anonfun$performInsertWithGenKeys$2.apply(Driver.scala:305)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:677)
	at net.liftweb.db.DB$$anonfun$14.apply(DB.scala:676)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.db.DB$class.runPreparedStatement(DB.scala:675)
	at net.liftweb.db.DB$class.prepareStatement(DB.scala:618)
	at net.liftweb.db.DB$$anon$1.prepareStatement(DB.scala:40)
	at net.liftweb.db.PostgreSqlDriver$.performInsertWithGenKeys(Driver.scala:304)
	at net.liftweb.db.DriverType.performInsert(Driver.scala:94)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:919)
	at net.liftweb.mapper.MetaMapper$$anonfun$20.apply(MetaMapper.scala:867)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.mapper.MetaMapper$class.save(MetaMapper.scala:866)
	at code.model.dataAccess.ResourceUser$.save(ResourceUser.scala:81)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply$mcZ$sp(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.mapper.Mapper$$anonfun$save$1.apply(Mapper.scala:88)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.util.Safe$.runSafe(Safe.scala:36)
	at net.liftweb.mapper.Mapper$class.runSafe(Mapper.scala:54)
	at code.model.dataAccess.ResourceUser.runSafe(ResourceUser.scala:40)
	at net.liftweb.mapper.Mapper$class.save(Mapper.scala:87)
	at code.model.dataAccess.ResourceUser.net$liftweb$mapper$ManyToMany$$super$save(ResourceUser.scala:40)
	at net.liftweb.mapper.ManyToMany$class.save(ManyToMany.scala:42)
	at code.model.dataAccess.ResourceUser.net$liftweb$mapper$OneToMany$$super$save(ResourceUser.scala:40)
	at net.liftweb.mapper.OneToMany$class.save(OneToMany.scala:50)
	at code.model.dataAccess.ResourceUser.save(ResourceUser.scala:40)
	at code.model.dataAccess.AuthUser.save(AuthUser.scala:117)
	at net.liftweb.mapper.MetaMegaProtoUser$MyUserBridge.save(ProtoUser.scala:294)
	at net.liftweb.proto.ProtoUser$class.actionsAfterSignup(ProtoUser.scala:708)
	at code.model.dataAccess.AuthUser$.actionsAfterSignup(AuthUser.scala:161)
	at code.model.dataAccess.AuthUser$.code$model$dataAccess$AuthUser$$testSignup$1(AuthUser.scala:654)
	at code.model.dataAccess.AuthUser$$anonf$$$$14ed75e461dcc9dcb494bed545fb1798$$$$innerSignup$1$1.apply$mcV$sp(AuthUser.scala:674)
	at code.model.dataAccess.AuthUser$$anonf$$$$14ed75e461dcc9dcb494bed545fb1798$$$$innerSignup$1$1.apply(AuthUser.scala:674)
	at code.model.dataAccess.AuthUser$$anonf$$$$14ed75e461dcc9dcb494bed545fb1798$$$$innerSignup$1$1.apply(AuthUser.scala:674)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at net.liftweb.http.S$NFuncHolder$$anonfun$apply$4.apply(S.scala:185)
	at scala.collection.immutable.List.map(List.scala:273)
	at net.liftweb.http.S$NFuncHolder.apply(S.scala:185)
	at net.liftweb.http.S$ProxyFuncHolder.apply(S.scala:114)
	at net.liftweb.http.LiftSession$$anonfun$net$liftweb$http$LiftSession$$buildFunc$1$2.apply(LiftSession.scala:783)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21$$anonfun$apply$37.apply(LiftSession.scala:797)
	at scala.collection.immutable.List.map(List.scala:277)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:797)
	at net.liftweb.http.LiftSession$$anonfun$21.apply(LiftSession.scala:788)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at net.liftweb.http.LiftSession.runParams(LiftSession.scala:787)
	at net.liftweb.http.LiftSession.processRequest(LiftSession.scala:1234)
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$dispatchStatefulRequest(LiftServlet.scala:423)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
	at net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$currentConn$.run(DB.scala:686)
	at net.liftweb.db.DB$class.use(DB.scala:698)
	at net.liftweb.db.DB$$anon$1.use(DB.scala:40)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
	at net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
	at net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
	at net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
	at net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.withReq(S.scala:1685)
	at net.liftweb.http.S$.withReq(S.scala:47)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:605)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
	at net.liftweb.http.S$class.init(S.scala:1284)
	at net.liftweb.http.S$.init(S.scala:47)
	at net.liftweb.http.LiftServlet.doSession$1(LiftServlet.scala:300)
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:310)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148)
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147)
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:346)
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34)
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:365)
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34)
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147)
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1327)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60)
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74)
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1022)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marko-md** [comment]
@sebtesobe According to the code it happens after sign up. Can you take a look at the current value of PK  of table ResourceUser?

**Comment by sebtesobe** [comment]
There is no field with 'pk' in its name in table `resourceuser`. PK probably resolves to `id` in that table, tho.
```
obp=# select * from resourceuser where id = 2;
 id |          email          | name_ |            provider_            |       providerid        | userid_ 
----+-------------------------+-------+---------------------------------+-------------------------+---------
  2 | foo@example.com |       | https://api.openbankproject.com | foo@example.com | 
```

The example above is taken from api.o.c, but the exception happens on multiple sandboxes for different users. I do not know if it happens to all users.

**Comment by marko-md** [comment]
I try to see does the primary key counter for table `resourceuser` is restarted and try to overwrite an existing row or we have a code issue.

**Comment by sebtesobe** [comment]
For the record, i tried those commands on the database for apisandbox.o.c with no success so far:

```
# REINDEX INDEX resourceuser_pk;
# REINDEX TABLE resourceuser;
```

I will do more research if there is something which can be done on the database level. On the other hand, maybe there is some sort of bookkeeping gone wrong on the API / Lift level?

**Comment by sebtesobe** [comment]
I believe to have found the fix:

```sql
SELECT setval('resourceuser_id_seq', max(id)) from resourceuser;
SELECT setval('authuser_id_seq', max(id)) from authuser;
```

This made sign up work again on apisandbox.o.c. . I will execute this on the other sandboxes to which i deployed on monday and if the exceptions will stop coming in, i'd ask you to add this to the documentation for migration 0000004 (or i can do it if you prefer)

**Comment by sebtesobe** [comment]
Alright, i did not get any exceptions like the above after applying the fix. @marko-md do you want me to add it to the migration script in the repo?

**Comment by marko-md** [comment]
@sebtesobe Yes please.

**Comment by sebtesobe** [comment]
Done, thanks for your help.
