### ISSUE TITLE
net.liftweb.json.JsonParser$ParseException: unknown token

### ISSUE THREAD

**Issue by sebtesobe** [OpenBankProject/OBP-API#596]
A few exceptions like this have popped up recently on https://bnpparibas-irb.openbankproject.com:

```
Sat Jun 10 09:50:42 UTC 2017: net.liftweb.json.JsonParser$ParseException: unknown token <
Near: <h
	at net.liftweb.json.JsonParser$Parser.fail(JsonParser.scala:234)
	at net.liftweb.json.JsonParser$Parser.nextToken(JsonParser.scala:321)
	at net.liftweb.json.JsonParser$$anonfun$2.apply(JsonParser.scala:188)
	at net.liftweb.json.JsonParser$$anonfun$2.apply(JsonParser.scala:141)
	at net.liftweb.json.JsonParser$.parse(JsonParser.scala:80)
	at net.liftweb.json.JsonParser$.parse(JsonParser.scala:45)
	at net.liftweb.json.package$.parse(package.scala:41)
	at code.search.elasticsearch$$anonfun$getAPIResponse$2.apply(search.scala:75)
	at code.search.elasticsearch$$anonfun$getAPIResponse$2.apply(search.scala:72)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by bupscale** [comment]
Any update on this dude?
